//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q4TM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTaskList
    {
        public int TaskId { get; set; }
        public string EmpId { get; set; }
        public System.DateTime TaskDate { get; set; }
        public string Task { get; set; }
        public string Type_Of_Task { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public string Status_Percentage { get; set; }
        public string Quadrant_Id { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual Quadrant Quadrant { get; set; }
    }
}
