//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTM4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSREntities : DbContext
    {
        public TSREntities()
            : base("name=TSREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Task> Employee_Task { get; set; }
        public virtual DbSet<EmployeeTaskList> EmployeeTaskLists { get; set; }
        public virtual DbSet<TasksImpNurg> TasksImpNurgs { get; set; }
        public virtual DbSet<TasksImpUrg> TasksImpUrgs { get; set; }
        public virtual DbSet<TasksNimpNurg> TasksNimpNurgs { get; set; }
        public virtual DbSet<TasksNimpUrg> TasksNimpUrgs { get; set; }
    }
}
