//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTM4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Task
    {
        public int TaskId { get; set; }
        public string EmpId { get; set; }
        public string Task { get; set; }
        public string Type_Of_Work { get; set; }
    }
}
